# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [7]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [8]:
A = np.arange(1, 16).reshape(3,5)

In [16]:
print(A.ndim)
print(A.shape)
print(A.size)
print(A.dtype)

2
(3, 5)
15
int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [17]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [18]:
B - C

array([[-1.,  0.,  1.],
       [ 2.,  3.,  4.],
       [ 5.,  6.,  7.]])

In [19]:
B * C

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.],
       [14., 16., 18.]])

In [21]:
B @ C

array([[12., 12., 12.],
       [30., 30., 30.],
       [48., 48., 48.]])

### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [ ]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

In [52]:
print(np.exp(B))
print(f"The minimum value in matrix is {B.min()}")
print(B.min(axis=1))
print(B.min(axis=0))
print(np.argmin(B))
print(np.argmin(B, axis=1))
print(f"Sum of matrix is {B.sum()}")
print(f"The mean for each column is {B.mean(axis=0)}")
print(f"The median for each column is {np.median(B, axis=0)}")

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
The minimum value in matrix is 1
[1 4 7]
[1 2 3]
0
[0 0 0]
Sum of matrix is 45
The mean for each column is [4. 5. 6.]
The median for each column is [4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [53]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [54]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

I och med att man inte anger fler index så blir det inte lika specifikt och då antar Numpy att man vill komma åt alla värden i det index som anges.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [58]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [57]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [59]:
for element in A.flat:
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [60]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


I koden skapas en array med 30 värden från 0 - 29. Sedan skapas en variabel b som skall motsvara variabel a(array) med de 30 elementen. Dessa skall sättas in i de två matriser som nu skapas, där varje matris skall bestå av 3 rader. -1 i uttrycket medför att Numpy auomatiskt räknar ut hur många kolumner som behöver skapas i varje matris för att kunna stoppa in alla de 30 elementen vilket i vårt fall blir 5 kolumner. Så dimensionen blir 2 matriser med vardera 3 rader och 5 kolumner.

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [61]:
# m1 = np.array([[1, 2], [3, 4]])
# m2 = np.array([1, 1])
# print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [62]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [63]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [156]:
def add_mult_matrices(A, B, operation):
     if isinstance(A, np.ndarray) and isinstance(B, np.ndarray):
     
        if operation == "add":
            if A.shape == B.shape: #Kontrollera dimension innan addition
                return A + B
            else:
                return "Not defined"

        elif operation == "multiply":
            if A.shape[1] == B.shape[0]: #Kontrollera dimensioner innan multiplikation av matriser
                return A @ B
            else:
                return "Not defined"
        
        else:
            return "Choose either 'add' or 'multiply'."
        
     else:
         return "A or B is not an np.ndarray"

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [101]:
print("Uppgift 10.1.1")
x = np.array([4, 3])
# 10.1.1
# a) vilken dimension har vektorn?
print("a.)", "Dimensionen är 1 x 2")

# b) Beräkna 5x
print("b.)", x * 5)

# c) Beräkna 3x
print("c.)", x * 3)

# d) Beräkna 5x + 3x
print("d.)", x*5 + 3*x)

# e) Beräkna 8x
print("e.)", x * 8)

# f) Beräkna 4x - x
print("f.)", 4*x - x)

# g) Beräkna x^T
print("g.)", "[4, 3] får dimension 2x1")

# h) Är x + x*t definierat?
print("h.)", "Nej, eftersom dem inte har samma dimensioner.")

# i) Beräkna ||x||
print("i.)", np.linalg.norm(x))


Uppgift 10.1.1
a.) Dimensionen är 1 x 2
b.) [20 15]
c.) [12  9]
d.) [32 24]
e.) [32 24]
f.) [12  9]
g.) [4, 3] får dimension 2x1
h.) Nej, eftersom dem inte har samma dimensioner.
i.) 5.0


In [111]:
print("Uppgift 10.1.2")
v = np.array([[3], [7], [0], [11]])
# 10.1.2
# a) vilken dimension har vektorn?
print("a.)", "Dimensionen är 4 x 1")

# b) Beräkna 2v
print("b.)\n", v * 2)

# c) Beräkna 5v + 2v
print("c.)\n", v*5 + v*2)

# d) Beräkna 4v - 2v
print(v.reshape(1, 4))

# e) Beräkna 8x
print("e.)\n", x * 8)

# f) Beräkna ||v||
print("f.)", "kvadratroten 179,", np.linalg.norm(v))

Uppgift 10.1.2
a.) Dimensionen är 4 x 1
b.)
 [[ 6]
 [14]
 [ 0]
 [22]]
c.)
 [[21]
 [49]
 [ 0]
 [77]]
[[ 3  7  0 11]]
e.)
 [[24]
 [56]
 [ 0]
 [88]]
f.) kvadratroten 179, 13.379088160259652


In [118]:
print("Uppgift 10.1.3")
v1 = np.array([4, 3, 1, 5])
v2 = np.array([2, 3, 1, 1])
# 10.1.3
# a) Beräkna ||v1||
print("a.)", "kvadratroten 51,", np.linalg.norm(v1))

# b) Beräkna ||v1 - v2||
print("b.)", "kvadratroten 20 = 2 kvadratroten 5,", np.linalg.norm(v1 - v2))

Uppgift 10.1.3
a.) kvadratroten 51, 7.14142842854285
b.) kvadratroten 20 = 2 kvadratroten 5, 4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [136]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])
C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])
E = np.array([[1], [2]])
I = np.array([[1, 0], [0, 1]])

In [161]:
print("Uppgift 10.2.1")
# 10.2.1
# a) 2A
print("a.\n",2 * A)
#print(add_mult_matrices())

# b) B - 2A
print("b.)\n", B - 2*A)

# c) Beräkna 3C - 2E
print("c.) Ej definierad")

# d) 2D - 3C
print("d.)\n", 2*D - 3*C)

# e) D^t + 2D
print("e.)\n", D.T + 2*D)

# f) 2C^t - 2D^T
print("f.)\n", 2*C.T - 2*D.T)

# g) A^T - B
print("g.) Ej definierad")

# h) AC
print("h.) Ej definierad eftersom antalet kolumner i A inte matchar antalet rader i C.")

# i) CD
print("i.)\n",add_mult_matrices(C, D, "multiply"))

# j) CB
print("j.)\n",add_mult_matrices(C, B, "multiply"))

# k) CI
print("k.)\n",add_mult_matrices(C, I, "multiply"))

# l) AB^T
print("l.)\n",add_mult_matrices(A, B.T, "multiply"))

Uppgift 10.2.1
a.
 [[ 4  2 -2]
 [ 2 -2  2]]
b.)
 [[ 0 -4  3]
 [ 0 -2 -4]]
c.) Ej definierad
d.)
 [[3 2]
 [2 3]]
e.)
 [[ 9 12]
 [12  9]]
f.)
 [[-4 -4]
 [-4 -4]]
g.) Ej definierad
h.) Ej definierad eftersom antalet kolumner i A inte matchar antalet rader i C.
i.)
 [[11 10]
 [10 11]]
j.)
 [[  8 -10  -3]
 [ 10  -8   0]]
k.)
 [[1 2]
 [2 1]]
l.)
 [[5 2]
 [7 4]]


In [163]:
A = np.array([[2, 3, 4], [5, 4, 1]])

print("Uppgift 10.2.2")
print(add_mult_matrices(A, A.T, "multiply"))

Uppgift 10.2.2
[[29 26]
 [26 42]]


In [172]:
A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

print("Uppgift 10.2.3")
print()
print("Resultatet av AB är ")
print(add_mult_matrices(A, B, "multiply"))
print()
print("och resultatet av AC är")
print(add_mult_matrices(A, C, "multiply"))
print()
print("Vi ser att multiplikation av AB och AC ger samma resultat.\nNu skall vi se vad BC ger.")
print()
print(add_mult_matrices(B, C, "multiply"))
print()
print("Vi ser BC inte ger samma resultat som de andra matrismultiplikationerna.")



Uppgift 10.2.3

Resultatet av AB är 
[[ 4  7]
 [ 8 14]]

och resultatet av AC är
[[ 4  7]
 [ 8 14]]

Vi ser att multiplikation av AB och AC ger samma resultat.
Nu skall vi se vad BC ger.

[[8 8]
 [4 9]]

Vi ser BC inte ger samma resultat som de andra matrismultiplikationerna.


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [173]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


Genom att använda .base så kan man se om det returnerar värdet None eller ej. Om det returnerar värdet None så är det en kopia.

In [177]:
v2[-1] = 123
v2

array([  2, 123])

In [178]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[  0   1   2 123]


In [179]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
